services:
  postgres:
    image: postgres:17

    container_name: mcqzone-postgres

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
    # without this if the container stops then all the data will be lost. So we need to mount a volume to persist the data.
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: