services:
  postgres:
    image: postgres:17

    container_name: mcqzone-postgres

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      # Persist PostgreSQL data
      - postgres_data:/var/lib/postgresql/data

      # Execute SQL files on first database creation
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: